name: Crowdin Synchronisation

on:
  push:
    branches:
      - next
    paths:
      - "**.po"
      - "crowdin.yml"
  # Run a GitHub Action on demand, without having to push to next
  workflow_dispatch:
  # Forward comments in .po files from Crowdin PRs to the translator in Crowdin
  pull_request_review_comment:

jobs:
  synchronize-with-crowdin:
    uses: warp-ds/reusable-workflows/.github/workflows/crowdin-sync.yml@main
    secrets: inherit
    with:
      pull_request_reviewers: "imprashast"
