name: Crowdin Synchronisation

on:
  push:
    branches: [next, main]

jobs:
  synchronize-with-crowdin:
    uses: warp-ds/reusable-workflows/.github/workflows/crowdin-sync.yml@main
    secrets: inherit
