name: Release
on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - name: Build
        run: pnpm build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Eik login and publish
        run: pnpm eik login -k $EIK_TOKEN && pnpm eik publish && pnpm eik pkg-alias || true
        env:
          EIK_TOKEN: ${{ secrets.EIK_TOKEN }}
